"use strict";
let s = "Hello World";
console.log(s.charAt(6));
console.log(s.split(' '));
console.log(s.toLocaleUpperCase());
console.log(s.indexOf('l'));
console.log(s.concat(' xyz'));
let strs = ['xyz', 'qwe', 'qwer', 'gnrt'];
console.log(strs);
let strs1 = ['qweert', 'vcbcvb', 'asdda'];
console.log(strs1);
let nums = ['qwe', 12, 34, 'rtty'];
let nums1 = ['ecs', 13, 45, 65];
console.log(nums);
console.log(nums1);
var emp;
emp = [1, 'kunal'];
console.log(emp);
